### ISSUE TITLE
action function in /resources/subscribe not working

### ISSUE THREAD

**Issue by simmondsty** [ShafSpecs/remix-pwa#22]
Hello,

Please could you help, I am able to get the subscription from the user using the default code but the /resources/subscribe post is not working from entry.client.tsx:

`await fetch("./resources/subscribe", {
	method: "POST",
	body: JSON.stringify({
		subscription: subscription,
		type: "POST_SUBSCRIPTION"
	})
});`

Is this meant to work by default or is there a reason the loader is working but not the action?

**Comment by ShafSpecs** [comment]
The loader fires once. And that's when the fetch is made to that route in `entry.client.tsx`. You can fire it manually tho by fetching that route, you need to pass a message to it tho

**Comment by ShafSpecs** [comment]
Btw, I am noticing a fetch to `./resources/subscribe` not `/resources/subscribe`. That is from the template but I am wondering if the "." is supposed to be there 🤔🤔. Doesn't seem to be the cause though

I would look at it later 👍

**Comment by simmondsty** [comment]
I have tried removing the "." but as you say, it fixes the route but it's
not making a difference.

Thanks for looking into it.

**Comment by GetCurious** [comment]
I think I have the same issue. Cant get pass 2nd this.
```jsx
navigator.serviceWorker.ready
  .then((registration) => {
    const subscription = registration.pushManager.getSubscription();
    return { subscription, registration };
  })
  .then(async (sub) => {
    if (await sub.subscription) {
      return sub.subscription;
    }

    const subInfo = await fetch("/resources/subscribe");
    const returnedSubscription = await subInfo.text();

    const convertedVapidKey = urlBase64ToUint8Array(returnedSubscription);

    const subscribe = sub.registration.pushManager.subscribe({
      userVisibleOnly: true,
      applicationServerKey: convertedVapidKey,
    });
    
    // Uncaught (in promise) DOMException: Registration failed - push service error
    console.log('subscribe', subscribe.catch((error) => console.log(error)));

    return subscribe;
  })
  .then(async (subscription) => {
    await fetch("./resources/subscribe", {
      method: "POST",
      body: JSON.stringify({
        subscription: subscription,
        type: "POST_SUBSCRIPTION",
      }),
    });
  });
```

**Comment by ShafSpecs** [comment]
> This issue has been de-activated due to inactivity and an assumption that this issue has been sorted out. This would remain unlocked to allow continuous discussion. 

> v0.8.2 is on it's way with a fix for this.
