### ISSUE TITLE
Causing double fetch and Prefetch not included in header

### ISSUE THREAD

**Issue by GetCurious** [ShafSpecs/remix-pwa#23]
steps to reproduce:
1. `npx create-remix --template remix-run/indie-stack blog-tutorial`
    >. ? Do you want me to run `npm install`? No
2. `pnpm i`
3. Add `prefetch="intent"` to `<Link>`

`Purpose: prefetch ` in Request header from chrome devtools. ✅ 
```
GET /notes?_data=routes%2Fnotes HTTP/1.1
Accept: application/signed-exchange;v=b3;q=0.7,*/*;q=0.8
Accept-Encoding: gzip, deflate, br
Accept-Language: en,zh;q=0.9,fil;q=0.8
Connection: keep-alive
Cookie: __session=eyJ1c2VySWQiOiJjbDNrd3E2b2EwMDAyY2dheW44emM2bmM5In0%3D.mvQL20%2B0LlAVOzRUhhAASRAUzSPZopsiUJSY2UUGdhs
Host: localhost:3000
Purpose: prefetch 
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: no-cors
Sec-Fetch-Site: same-origin
Sec-GPC: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.61 Safari/537.36
```

4. `npx remix-pwa@latest`
5.  `pnpm i`
6. setup VAPID_KEYS

`Purpose: prefetch` missing. ❌ 
```
GET /notes?_data=routes%2Fnotes HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en,zh;q=0.9,fil;q=0.8
Connection: keep-alive
Cookie: __session=eyJ1c2VySWQiOiJjbDNrd3E2b2EwMDAyY2dheW44emM2bmM5In0%3D.mvQL20%2B0LlAVOzRUhhAASRAUzSPZopsiUJSY2UUGdhs
Host: localhost:3000
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: no-cors
Sec-Fetch-Site: same-origin
Sec-GPC: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.61 Safari/537.36
```
![image](https://user-images.githubusercontent.com/8876854/170166120-5ec8ab2e-fdd8-4ea2-a2ea-8567c6823b13.png)
![image](https://user-images.githubusercontent.com/8876854/170166799-f9595601-8a83-48ba-a822-b5d266123bb7.png)

Personal usage: caching request
https://sergiodxa.com/articles/fix-double-data-request-when-prefetching-in-remix#cache-every-loader-request

**Comment by ShafSpecs** [comment]
> _Image_

Is this the loader of the pre-fetched link? Or the current route? `remix-pwa` shouldn't alter the behaviour of the "intent" attribute of a prefetch

**Comment by GetCurious** [comment]
I added the loader to this route.
https://github.com/remix-run/remix/blob/main/examples/blog-tutorial/app/routes/notes/index.tsx

**Comment by ShafSpecs** [comment]
> I added the loader to this route. https://github.com/remix-run/remix/blob/main/examples/blog-tutorial/app/routes/notes/index.tsx FYI last i check on firefox, I received `Moz-Purpose: prefetch`

Weird, I would try to re-create it and look at it.

**Comment by ShafSpecs** [comment]
Did additional research on prefetching and learned that they clash in the browser, if we disconnect the SW, it works as normal.

**Comment by ShafSpecs** [comment]
The double fetch isn't a remix-pwa specific issue, it happens in some non-PWA projects too. Best do is add a duplicate checker if you don't want double data
