### ISSUE TITLE
Cannot read properties of undefined (reading 'addEventListener')

### ISSUE THREAD

**Issue by ABSanthosh** [ShafSpecs/remix-pwa#27]
`Cannot read properties of undefined (reading 'addEventListener') at entry.worker.js:156:6`

I'm getting this error from public/entry.worker.js
Tried to fix it but nothing seems to work.

**Comment by ShafSpecs** [comment]
`self` is of type `ServiceWorkerGlobalScope`. Js probably doesn't realize this yet. I would look at it and try to solve it :+1:

**Comment by ShafSpecs** [comment]
@ABSanthosh try removing `let self;` from [line 5](https://github.com/ShafSpecs/remix-pwa/blob/6d09dfbff763130e2cfaac21344f735b7a935734/templates/js/app/entry.worker.js#L5) in the `entry.worker.js`

**Comment by ShafSpecs** [comment]
Fixed @ABSanthosh :smile:.
https://github.com/ShafSpecs/remix-pwa/commit/e8ead3130226ed77a3d16fac6294ddc7b01a3e24
