### ISSUE TITLE
Serialization of REMIX_NAVIGATION messages

### ISSUE THREAD

**Issue by wKovacs64** [ShafSpecs/remix-pwa#32]
Hey @ShafSpecs, congratulations on the v1 release! 🎉 

I noticed in https://github.com/ShafSpecs/remix-pwa/commit/32bbd7551396f2115a53b85235911af9879f1edb you started serializing the `REMIX_NAVIGATION` messages with `JSON.stringify` but they are not deserialized with `JSON.parse` [in the service worker](https://github.com/ShafSpecs/remix-pwa/blob/78e929804d0a9b5a7a6849e26fab1fa2433d1ab9/templates/ts/app/entry.worker.ts#L31). I don't think this works, does it?

**Comment by ShafSpecs** [comment]
OMG! 🤦. I would patch it this morning

**Comment by ShafSpecs** [comment]
It skipped my mind. Tbh, I would remove serialization of the message for now. Because, it is kind of a powerful tool in the SW and I didn't fully implement it.

**Comment by ShafSpecs** [comment]
Fixed the issue already :+1:
