### ISSUE TITLE
base 64 decoding

### ISSUE THREAD

**Issue by cjenaro** [ShafSpecs/remix-pwa#34]
There are a couple of issues with the function linked below

https://github.com/ShafSpecs/remix-pwa/blob/077251e9c25e4a19754aa846b0d790e9f53f7c98/templates/ts/app/push.entry.client.ts#L1

1. The replace function is using an unneeded escaped character
2. The function is logging the following error: "The string to be decoded is not correctly encoded."

I don't quite understand the idea of how the key needs to look like after encoding, but this is the result here: `'BPMc6qUvK0NNK3UX7+7s+fmd1CkkEmkghHHvz0qMLFbeuHOE4YTQHNNb3EBmgottwCNAgEyXqnK3DCAJB8MNPyI',==`

**Comment by ShafSpecs** [comment]
Weird. Replace your function with this.:
```js
    let binary_string = window.atob(base64String);
    let len = binary_string.length;
    let bytes = new Uint8Array(len);
    for (var i = 0; i < len; i++) {
        bytes[i] = binary_string.charCodeAt(i);
    }
    return bytes.buffer;
```

**Comment by ShafSpecs** [comment]
First time I am seeing this kind of error :smile:

**Comment by cjenaro** [comment]
Replace the whole function? I mean the whole padding bit would be missed here right?

**Comment by ShafSpecs** [comment]
> Replace the whole function? I mean the whole padding bit would be missed here right?

Yes

**Comment by ShafSpecs** [comment]
> Replace the whole function? I mean the whole padding bit would be missed here right?

Yes
