### ISSUE TITLE
css files Caching

### ISSUE THREAD

**Issue by DaRkS0** [ShafSpecs/remix-pwa#40]
sorry I'm a bit newbie to react 
but how to Cache css files or should I use styled components 
just asking coz on offline css files are missing thx

**Comment by ShafSpecs** [comment]
CSS assets are also cached with remix-pwa :thinking:. Would optimise the asset caching tho

**Comment by DaRkS0** [comment]
> CSS assets are also cached with remix-pwa thinking. Would optimise the asset caching tho

sorry for asking you but can you give me an example 
like i said i'm a newbie

**Comment by ShafSpecs** [comment]
I mean CSS is supposed to be cached too. I would try to improve it on my side though :v:

**Comment by ShafSpecs** [comment]
> > CSS assets are also cached with remix-pwa thinking. Would optimise the asset caching tho
> 
> sorry for asking you but can you give me an example like i said i'm a newbie

![cache](https://user-images.githubusercontent.com/69679506/209159015-89835127-4e35-4fa1-9363-636d663ae9d9.png)

The CSS gets cached as well. If you check the headers, it is not re-fetching the CSS file from the server but instead using the one in cache. 

This is an application that is currently in production btw.

**Comment by ShafSpecs** [comment]
*This issue has been resolved*
