### ISSUE TITLE
ServiceWorker never registered because `entry.client.jsx#window.addEventListener("load", ...)` is never triggered

### ISSUE THREAD

**Issue by nuKs** [ShafSpecs/remix-pwa#42]
Hello,

I've just installed remix-pwa@latest on a pristine remix@1.7.2 app (no template, using remix server). The service worker is never registered, I managed to pinpoint the problem to the lack of triggering of the `window.addEventListener("load", ...)` but can't manage to solve the issue.
This happens both in dev and prod deployments.

Changing to `window.addEventListener("click", ...)` does work.
 
![Screen Shot 2022-09-28 at 8 27 07 AM](https://user-images.githubusercontent.com/1691962/192778511-68bfad58-7240-485c-b21b-59be445fe29b.png)
![Screen Shot 2022-09-28 at 8 25 25 AM](https://user-images.githubusercontent.com/1691962/192778525-5cae2c02-92bd-4d56-a85b-f478b12362a0.png)
![Screen Shot 2022-09-28 at 8 26 24 AM](https://user-images.githubusercontent.com/1691962/192778540-497b7053-0ff4-44dd-b8ab-fb41b89acfe3.png)

Any insight welcome :-)
- Regards.

**Comment by ShafSpecs** [comment]
Thank you. I would look at it over the weekend :+1:

**Comment by halindraprakoso** [comment]
hello, any updates about this? facing the same issue

**Comment by EugenEistrachKC** [comment]
You might have some other issue. For me it works fine. Which browser are you using ?

**Comment by halindraprakoso** [comment]
good point. Basically I have the same situation mentioned above where the load event seemingly wasn't triggered (or the listener wasn't added). `if ("serviceWorker" in navigator)` returns true though. Changing to click did register the service worker. I was using chrome for that. After testing, the service worked registered just fine on firefox, but not on chrome and safari.

**Comment by ShafSpecs** [comment]
> hello, any updates about this? facing the same issue

Nope. Seemed okay to me. I even ran it in an isolated VM to make sure it wasn't any of my settings and it ran just fine

**Comment by nuKs** [comment]
> > hello, any updates about this? facing the same issue
> 
> Nope. Seems okay to me. I even ran it on a different machine to make sure it wasn't any of my settings and it ran just fine

Thanks for the follow up.
Could you quickly write the process you've used to setup the app so I can test your setup?
ie.
(considering node 18 -- optional I think it wont impact)
1. (important: is it indie stack or no stack or stg else?) install remix (latest) `npx create-remix@latest --template remix-run/indie-stack`.
2. install remix pwa (latest) `npx remix-pwa@latest`
3. use javascript instead of typescript
4. Just-In-Time Caching
5. no additional remix-pwa services

**Comment by halindraprakoso** [comment]
just revisited the project. the window load event now fires as expected on chrome and safari, therefore my issue is resolved. Probably it was a browser bug?

**Comment by ShafSpecs** [comment]
Perhaps. Happy to hear it's been fixed :blush:

**Comment by ShafSpecs** [comment]
*This issue is closed due to the issue being resolved. If you have any other issue or further comment, please open a new issue*
