### ISSUE TITLE
ServiceWorker never registered because entry.client.jsx#window.addEventListener("load", ...) is never triggered

### ISSUE THREAD

**Issue by nuKs** [ShafSpecs/remix-pwa#44]
Reopening issue https://github.com/ShafSpecs/remix-pwa/issues/42.

-- 

Hello,

I've just installed remix-pwa@latest on a pristine remix@1.7.2 app (no template, using remix server). The service worker is never registered, I managed to pinpoint the problem to the lack of triggering of the window.addEventListener("load", ...) but can't manage to solve the issue.
This happens both in dev and prod deployments.

Changing to window.addEventListener("click", ...) does work.

![image](https://user-images.githubusercontent.com/1691962/202927255-14125dd4-1e32-4710-a31e-36b93ca773aa.png)
![image](https://user-images.githubusercontent.com/1691962/202927260-d0072073-4e23-46f4-a2a6-f910a91bf3e5.png)
![image](https://user-images.githubusercontent.com/1691962/202927268-94fc9117-4668-4e31-80b7-0522cc427d28.png)

**Comment by nuKs** [comment]
Here is the solution: Register the service worker even if the page has already been loaded.

It works on desktop.

Also to consider regarding mobile (for pwa webapk, not yet tested, current code with fix works for pwa without webapk):  https://web.dev/install-criteria/

- Be served over HTTPS
- Meets the user engagement heuristics:
   1. The user needs to have clicked or tapped on the page at least once (at any time, even during a previous page load)
   2. The user needs to have spent at least 30 seconds viewing the page (at any time)


Source code:

```js
if ("serviceWorker" in navigator) {
  async function doStuffs() {
    return navigator.serviceWorker
      .register("/entry.worker.js") // , {scope: '/'}
      .then(() => navigator.serviceWorker.ready)
      .then(() => {
        if (navigator.serviceWorker.controller) {
          navigator.serviceWorker.controller.postMessage({
            type: "SYNC_REMIX_MANIFEST",
            manifest: window.__remixManifest,
          });
        } else {
          navigator.serviceWorker.addEventListener("controllerchange", () => {
            navigator.serviceWorker.controller?.postMessage({
              type: "SYNC_REMIX_MANIFEST",
              manifest: window.__remixManifest,
            });
          });
        }
      })
      .catch((error) => {
        console.error("Service worker registration failed", error);
      });
  }
    
  if (document.readyState === "complete" || document.readyState === "interactive") {
    doStuffs();
  }
  else {
    window.addEventListener("load", () => {
      doStuffs();
    });
  }
}
```

**Comment by nuKs** [comment]
actually might be interesting to merge within the repo if anyone find this solves their issue (in such case, can you write it here?)

**Comment by ShafSpecs** [comment]
> actually might be interesting to merge within the repo if anyone find this solves their issue (in such case, can you write it here?)

That would be very welcoming and appreciated. I haven't been able to update the package including fixes that's been glaring at me for a while, thx to school and work =)

**Comment by ShafSpecs** [comment]
Okay. Thank you very much, this issue has been fixed.

I would bundle it with the new update that should roll out next year :+1:
