### ISSUE TITLE
Installation with Yarn

### ISSUE THREAD

**Issue by chiangs** [ShafSpecs/remix-pwa#51]
Installing via Yarn (v1.22.19) does not show the CLI prompts.

Solution: 

Run `yarn add remix-pwa@latest`

Run `yarn remix-pwa --pwa`

Follow prompts, ***SKIP*** installing with NPM

Run `yarn install`

**Comment by ShafSpecs** [comment]
I am confused. Does the solution fix yarn installation issue with yarn? Or it is still an unsolved error?

**Comment by chiangs** [comment]
Depends on how you look at it.

If you use `npx` then it is all set up for you through the questions in the CLI.

Installing with Yarn does not do this at the moment, but if you follow the steps I listed above, then it will add the library, then run the command manually and then you get all the same CLI prompts. The key is to skip the `npm install` and manually run `yarn install` after since the choice from the CLI is `npm install`.

**Comment by ShafSpecs** [comment]
> Want me to make a PR to the docs? @ShafSpecs

Yes, you can make a PR.

I would need to add default support for yarn though :thinking:. So the package manager gets automatically detected and it runs the appropriate command.

**Comment by ShafSpecs** [comment]
> Depends on how you look at it.
> 
> If you use `npx` then it is all set up for you through the questions in the CLI.
> 
> Installing with Yarn does not do this at the moment, so installing with yarn doesn't do everything `npx` does, but if you follow the steps I listed above, then it will add the library, then run the command manually and then you get all the same CLI prompts.
> 
> The key is to skip the `npm install` and manually run `yarn install` after since the choice from the CLI is `npm install`.
> 
> Want me to make a PR to the docs? @ShafSpecs

This should be fixed in the next update :+1:, which is coming out soon

**Comment by ShafSpecs** [comment]
I am looking into auto-detecting your package manager so it runs the ones needed
