### ISSUE TITLE
Prompt skipped question for `app` directory.

### ISSUE THREAD

**Issue by dev-afzalansari** [ShafSpecs/remix-pwa#60]
This is because the `type` property is missing from the question itself. Another problem is that the name of that question is changed now i assume this is because of merging the `dev` branch.

**Comment by ShafSpecs** [comment]
> This is because the `type` property is missing from the question itself. Another problem is that the name of that question is changed now i assume this is because of merging the `dev` branch.

I would review this now :+1:

**Comment by ShafSpecs** [comment]
Are you on the `remix` discord btw? Or similar communities?
